---

- name: gomax integration backup
  hosts: gazellacom
  become: true
  roles:
    - role: gazellacom-backup
      gazellacom_mode: backup                         #backup, copyfromprod, restore, cleandb
      gazellacom_db_local_host: gomax-syscom-int.citzwq60niow.us-east-1.rds.amazonaws.com                          
      gazellacom_db_local_name: syscomdbintegration
      gazellacom_db_local_port: 5432      
      gazellacom_db_local_username: "{{ db_usernaame }}"                         
      gazellacom_db_local_password: "{{ db_password }}"               
      gazellacom_db_local_retention: 10                          
      gazellacom_project: gomax                       # client
      gazellacom_environment: integration             #integration, production
