---

- name: "Backup  {{ gazellacom_project }} - {{ gazellacom_environment }} "
  block:

    - name: Print message if ansible version is greater than 2.7.0
      debug:
        msg: "Ansible version is  {{ ansible_version.full }}"

    - name: Get timestamp from the system
      shell: "date +%Y%m%d-%H%M"
      register: tstamp

    - name: Set variables
      set_fact:
       my_date: "{{ tstamp.stdout[0:8]}}"
       my_time: "{{ tstamp.stdout[8:]}}"

    - name: "Ensure app workdir exists: {{ gazellacom_local_workdir }}"
      become: yes
      ansible.builtin.file:
        path: "{{ gazellacom_local_workdir }}"
        state: directory
#        owner: "{{ gazellacom_awx_user }}"
#        group: "{{ gazellacom_awx_group }}"
        mode: 0775
        force: yes

    - name: "Backup directory workdir exists: {{ gazellacom_local_workdir }}/backup"
      become: yes
      ansible.builtin.file:
        path: "{{ gazellacom_local_workdir }}/backup"
        state: directory
#        owner: "{{ gazellacom_awx_user }}"
#        group: "{{ gazellacom_awx_group }}"
        mode: 0775
        force: yes

    - name: "Log Directory workdir exists: {{ gazellacom_local_workdir }}/log"
      become: yes
      ansible.builtin.file:
        path: "{{ gazellacom_local_workdir }}/log"
        state: directory
#       owner: "{{ gazellacom_awx_user }}"
#        group: "{{ gazellacom_awx_group }}"
        mode: 0775
        force: yes

    - name: "Start PGDUMP for backup"
      ansible.builtin.command: "export PGPASSWORD={{ gazellacom_db_local_password }} ; pg_dump -h {{ gazellacom_db_local_host }} -U {{ gazellacom_db_local_username }} --exclude-table-data 'audit.*'  -Fc {{ gazellacom_db_local_name }} > {{ gazellacom_local_workdir }}/backup/{{ gazellacom_db_local_name }}-{{ my_date }}-{{ my_time }}.bkp "
      args:
        chdir: "{{ gazellacom_local_workdir }}/backup"

    - name: "Finish backup "
      ansible.builtin.command: "echo '[BACKUP] Creating backup {{ gazellacom_local_workdir }}/backu/{{ gazellacom_db_local_name }}-{{ my_date }}-{{ my_time}}.bkp from the database {{ gazellacom_db_local_name }}' >> {{ gazellacom_local_workdir }}/log/backup.log"

