---

- name: "Backup  {{ gazellacom_project }} - {{ gazellacom_environment }} "
  block:

    - name: Print message if ansible version is greater than 2.7.0
      debug:
        msg: "Ansible version is  {{ ansible_version.full }}"

    - name: Get timestamp from the system
      shell: "date +%Y%m%d-%H%M"
      register: tstamp

    - name: Set variables
      set_fact:
       my_date: "{{ tstamp.stdout[0:8]}}"
       my_time: "{{ tstamp.stdout[8:]}}"

    - name: "Ensure app workdir exists: {{ gazellacom_local_workdir }}"
      become: yes
      ansible.builtin.file:
        path: "{{ gazellacom_local_workdir }}"
        state: directory
#        owner: "{{ gazellacom_awx_user }}"
#        group: "{{ gazellacom_awx_group }}"
        mode: 0775
        force: yes

    - name: "Backup directory workdir exists: {{ gazellacom_local_workdir }}/remote"
      become: yes
      ansible.builtin.file:
        path: "{{ gazellacom_local_workdir }}/remote"
        state: directory
#        owner: "{{ gazellacom_awx_user }}"
#        group: "{{ gazellacom_awx_group }}"
        mode: 0775
        force: yes

    - name: "Clean all connection"
      become: yes
      ansible.builtin.shell: "export PGPASSWORD={{ gazellacom_db_local_password_main }} ; psql -h {{ gazellacom_db_local_host }} -p {{ gazellacom_db_local_port }}  -U {{ gazellacom_db_local_username_main }} -Fc -d template1 -c 'SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE pid <> pg_backend_pid() AND datname =  \"{{ gazellacom_db_local_name }}\" ;' "

#    - name: "Start RESTORING for backup"
#      become: yes
#      ansible.builtin.shell: "export PGPASSWORD={{ gazellacom_db_local_password }} ; pg_restore -h {{ gazellacom_db_local_host }} -p {{ gazellacom_db_local_port }} -j 30  -U {{ gazellacom_db_local_username }} -Fc -d {{ gazellacom_db_local_name }}   '{{ gazellacom_db_local_name }}-{{ my_date }}{{ my_time }}.bkp' "
#      args:
#        chdir: "{{ gazellacom_local_workdir }}/remote"

    - name: "Finish backup "
      become: yes
      ansible.builtin.shell: "echo '{{ my_date }}{{ my_time }} [BACKUP] Creating backup {{ gazellacom_local_workdir }}/backup/{{ gazellacom_db_local_name }}-{{ my_date }}{{ my_time}}.bkp from the database {{ gazellacom_db_local_name }}' >> {{ gazellacom_local_workdir }}/log/backup.log"

